const images = [
  {
    id: 1,
    src: "/images/photo2.png",
    alt: "Photo 1",
    table_id: "48z5pjps3ntvqc1b",
    table_name: "Auto-Roulette",
    gameProvider: "Evolution",
    subprovider: "",
    gameVertical: "Live",
    gameTypeName: "Roulette",
    gameTypeCode: "roulette",
  },
  {
    id: 2,
    src: "/images/photo2.png",
    alt: "Photo 2",
    table_id: "60i0lcfx5wkkv3sy",
    table_name: "Baccarat B DNT",
    gameProvider: "Evolution",
    subprovider: "",
    gameVertical: "Live",
    gameTypeName: "Baccarat",
    gameTypeCode: "baccarat",
  },
  {
    id: 3,
    src: "/images/photo2.png",
    alt: "Photo 3",
    table_id: "9dxyqtvp0rjqvu6r",
    table_name: "DNT Immersive Roulette",
    gameProvider: "Evolution",
    subprovider: "",
    gameVertical: "Live",
    gameTypeName: "Roulette",
    gameTypeCode: "roulette",
  },
  {
    id: 4,
    src: "/images/photo2.png",
    alt: "Photo 4",
    table_id: "AmericanTable001",
    table_name: "American Roulette",
    gameProvider: "Evolution",
    subprovider: "",
    gameVertical: "Live",
    gameTypeName: "American Roulette",
    gameTypeCode: "americanroulette",
  },
  {
    id: 5,
    src: "/images/photo2.png",
    alt: "Photo 5",
    table_id: "AndarBahar000001",
    table_name: "Super Andar Bahar",
    gameProvider: "Evolution",
    subprovider: "",
    gameVertical: "Live",
    gameTypeName: "Super Andar Bahar",
    gameTypeCode: "andarbahar",
  },
  {
    id: 6,
    src: "/images/photo2.png",
    alt: "Photo 6",
    table_id: "BacBo00000000001",
    table_name: "Bac Bo",
    gameProvider: "Evolution",
    subprovider: "",
    gameVertical: "Live",
    gameTypeName: "Bac Bo",
    gameTypeCode: "bacbo",
  },
  {
    id: 7,
    src: "/images/photo2.png",
    alt: "Photo 7",
    table_id: "BalloonRace00001",
    table_name: "Balloon Race DNT",
    gameProvider: "Evolution",
    subprovider: "",
    gameVertical: "Live",
    gameTypeName: "Balloon Race",
    gameTypeCode: "balloonrace",
  },
  {
    id: 8,
    src: "/images/photo2.png",
    alt: "Photo 8",
    table_id: "CFreeBetBj000001",
    table_name: "Free Bet Blackjack 1 DNT",
    gameProvider: "Evolution",
    subprovider: "",
    gameVertical: "Live",
    gameTypeName: "Classic Free Bet Blackjack",
    gameTypeCode: "classicfreebet",
  },
  {
    id: 9,
    src: "/images/photo2.png",
    alt: "Photo 9",
    table_id: "Craps00000000001",
    table_name: "Craps DNT",
    gameProvider: "Evolution",
    subprovider: "",
    gameVertical: "Live",
    gameTypeName: "Craps",
    gameTypeCode: "craps",
  },
  {
    id: 10,
    src: "/images/photo2.png",
    alt: "Photo 10",
    table_id: "CrazyCoinFlip001",
    table_name: "Crazy Coin Flip",
    gameProvider: "Evolution",
    subprovider: "",
    gameVertical: "Live",
    gameTypeName: "Crazy Coin Flip",
    gameTypeCode: "crazycoinflip",
  },
  {
    id: 11,
    src: "/images/photo2.png",
    alt: "Photo 11",
    table_id: "CrazyTime0000001",
    table_name: "Crazy Time",
    gameProvider: "Evolution",
    subprovider: "",
    gameVertical: "Live",
    gameTypeName: "Crazy Time",
    gameTypeCode: "crazytime",
  },
  //   {
  //     id: 12,
  //     src: "/images/photo12.png",
  //     alt: "Photo 12",
  //     table_id: "CSPTable00000001",
  //     table_name: "Caribbean Stud Poker",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Caribbean Stud Poker",
  //     gameTypeCode: "csp",
  //   },
  //   {
  //     id: 13,
  //     src: "/images/photo13.png",
  //     alt: "Photo 13",
  //     table_id: "dealnodeal000001",
  //     table_name: "Deal or No Deal",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Deal or No Deal",
  //     gameTypeCode: "dealnodeal",
  //   },
  //   {
  //     id: 14,
  //     src: "/images/photo14.png",
  //     alt: "Photo 14",
  //     table_id: "DHPTable00000001",
  //     table_name: "2 Hand Casino Holdem",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "2 Hand Casino Hold'em",
  //     gameTypeCode: "dhp",
  //   },
  //   {
  //     id: 15,
  //     src: "/images/photo15.png",
  //     alt: "Photo 15",
  //     table_id: "doasaloon0000001",
  //     table_name: "Dead or Alive: Saloon",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Dead or Alive: Saloon",
  //     gameTypeCode: "deadoralivesaloon",
  //   },
  //   {
  //     id: 16,
  //     src: "/images/photo16.png",
  //     alt: "Photo 16",
  //     table_id: "doasaloon0000002",
  //     table_name: "Dead or Alive: Saloon",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Dead or Alive: Saloon",
  //     gameTypeCode: "deadoralivesaloon",
  //   },
  //   {
  //     id: 17,
  //     src: "/images/photo17.png",
  //     alt: "Photo 17",
  //     table_id: "DoubleBallRou001",
  //     table_name: "Double Ball Roulette",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Roulette",
  //     gameTypeCode: "roulette",
  //   },
  //   {
  //     id: 18,
  //     src: "/images/photo18.png",
  //     alt: "Photo 18",
  //     table_id: "DragonTiger00001",
  //     table_name: "Dragon Tiger DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Dragon Tiger",
  //     gameTypeCode: "dragontiger",
  //   },
  //   {
  //     id: 19,
  //     src: "/images/photo19.png",
  //     alt: "Photo 19",
  //     table_id: "ETHTable00000001",
  //     table_name: "Extreme Texas Holdem",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Extreme Texas Hold'em",
  //     gameTypeCode: "eth",
  //   },
  //   {
  //     id: 20,
  //     src: "/images/photo20.png",
  //     alt: "Photo 20",
  //     table_id: "ExChEpicSpins001",
  //     table_name: "Extra Chilli Epic Spins",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Extra Chilli Epic Spins",
  //     gameTypeCode: "extrachilliepicspins",
  //   },
  //   {
  //     id: 21,
  //     src: "/images/photo21.png",
  //     alt: "Photo 21",
  //     table_id: "FanTan0000000002",
  //     table_name: "Fan Tan",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Fan Tan",
  //     gameTypeCode: "fantan",
  //   },
  //   {
  //     id: 22,
  //     src: "/images/photo22.png",
  //     alt: "Photo 22",
  //     table_id: "FreeBet000000001",
  //     table_name: "Free Bet Blackjack DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Free Bet Blackjack",
  //     gameTypeCode: "freebet",
  //   },
  //   {
  //     id: 23,
  //     src: "/images/photo23.png",
  //     alt: "Photo 23",
  //     table_id: "FunkyTime0000001",
  //     table_name: "Funky Time",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Funky Time",
  //     gameTypeCode: "funkytime",
  //   },
  //   {
  //     id: 24,
  //     src: "/images/photo24.png",
  //     alt: "Photo 24",
  //     table_id: "GoldVaultRo00001",
  //     table_name: "Gold Vault Roulette",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Roulette",
  //     gameTypeCode: "roulette",
  //   },
  //   {
  //     id: 25,
  //     src: "/images/photo25.png",
  //     alt: "Photo 25",
  //     table_id: "GonzoTH000000001",
  //     table_name: "Gonzo's Treasure Hunt DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Gonzo's Treasure Hunt",
  //     gameTypeCode: "gonzotreasurehunt",
  //   },
  //   {
  //     id: 26,
  //     src: "/images/photo26.png",
  //     alt: "Photo 26",
  //     table_id: "GonzoTM000000001",
  //     table_name: "Gonzo's Treasure Map",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Gonzo's Treasure Map",
  //     gameTypeCode: "gonzotreasuremap",
  //   },
  //   {
  //     id: 27,
  //     src: "/images/photo27.png",
  //     alt: "Photo 27",
  //     table_id: "HoldemTable00001",
  //     table_name: "Casino Hold'em",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Casino Hold'em",
  //     gameTypeCode: "holdem",
  //   },
  //   {
  //     id: 28,
  //     src: "/images/photo28.png",
  //     alt: "Photo 28",
  //     table_id: "ImperialQuest001",
  //     table_name: "Imperial Quest",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Money Wheel",
  //     gameTypeCode: "moneywheel",
  //   },
  //   {
  //     id: 29,
  //     src: "/images/photo29.png",
  //     alt: "Photo 29",
  //     table_id: "InstantRo0000001",
  //     table_name: "Instant Roulette",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Instant Roulette",
  //     gameTypeCode: "instantroulette",
  //   },
  //   {
  //     id: 30,
  //     src: "/images/photo30.png",
  //     alt: "Photo 30",
  //     table_id: "k2oswnib7jjaaznw",
  //     table_name: "Baccarat Control Squeeze",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Baccarat",
  //     gameTypeCode: "baccarat",
  //   },
  //   {
  //     id: 31,
  //     src: "/images/photo31.png",
  //     alt: "Photo 31",
  //     table_id: "leqi3kfevdqqanba",
  //     table_name: "DNT Speed Baccarat A",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Baccarat",
  //     gameTypeCode: "baccarat",
  //   },
  //   {
  //     id: 32,
  //     src: "/images/photo32.png",
  //     alt: "Photo 32",
  //     table_id: "lfdcsti5mzhaabvv",
  //     table_name: "Baccarat HLS.js Auto DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Baccarat",
  //     gameTypeCode: "baccarat",
  //   },
  //   {
  //     id: 33,
  //     src: "/images/photo33.png",
  //     alt: "Photo 33",
  //     table_id: "Lightning6000001",
  //     table_name: "Lightning Lotto DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Lightning Lotto",
  //     gameTypeCode: "lightninglotto",
  //   },
  //   {
  //     id: 34,
  //     src: "/images/photo34.png",
  //     alt: "Photo 34",
  //     table_id: "LightningBac0001",
  //     table_name: "Lightning Baccarat",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Baccarat",
  //     gameTypeCode: "baccarat",
  //   },
  //   {
  //     id: 35,
  //     src: "/images/photo35.png",
  //     alt: "Photo 35",
  //     table_id: "LightningDice001",
  //     table_name: "Lightning Dice",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Lightning Dice",
  //     gameTypeCode: "lightningdice",
  //   },
  //   {
  //     id: 36,
  //     src: "/images/photo36.png",
  //     alt: "Photo 36",
  //     table_id: "LightningStorm01",
  //     table_name: "Lightning Storm",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Lightning Storm",
  //     gameTypeCode: "lightningstorm",
  //   },
  //   {
  //     id: 37,
  //     src: "/images/photo37.png",
  //     alt: "Photo 37",
  //     table_id: "LightningTable01",
  //     table_name: "Lightning Roulette",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Roulette",
  //     gameTypeCode: "roulette",
  //   },
  //   {
  //     id: 38,
  //     src: "/images/photo38.png",
  //     alt: "Photo 38",
  //     table_id: "livespins0000000",
  //     table_name: "Bet with Streamers DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "Livespins",
  //     gameVertical: "Live",
  //     gameTypeName: "Bet with streamer",
  //     gameTypeCode: "betwithstreamer",
  //   },
  //   {
  //     id: 39,
  //     src: "/images/photo39.png",
  //     alt: "Photo 39",
  //     table_id: "lr6t4k3lcd4qgyrk",
  //     table_name: "Grand Casino Roulette DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Roulette",
  //     gameTypeCode: "roulette",
  //   },
  //   {
  //     id: 40,
  //     src: "/images/photo40.png",
  //     alt: "Photo 40",
  //     table_id: "MegaBall00000001",
  //     table_name: "Mega Ball",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "MegaBall",
  //     gameTypeCode: "megaball",
  //   },
  //   {
  //     id: 41,
  //     src: "/images/photo41.png",
  //     alt: "Photo 41",
  //     table_id: "MonBigBaller0001",
  //     table_name: "MONOPOLY Big Baller DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Monopoly Big Baller",
  //     gameTypeCode: "monopolybigballer",
  //   },
  //   {
  //     id: 42,
  //     src: "/images/photo42.png",
  //     alt: "Photo 42",
  //     table_id: "Monopoly00000001",
  //     table_name: "Monopoly Live",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Monopoly Live",
  //     gameTypeCode: "monopoly",
  //   },
  //   {
  //     id: 43,
  //     src: "/images/photo43.png",
  //     alt: "Photo 43",
  //     table_id: "MOWDream00000001",
  //     table_name: "DNT Dream Catcher",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Money Wheel",
  //     gameTypeCode: "moneywheel",
  //   },
  //   {
  //     id: 44,
  //     src: "/images/photo44.png",
  //     alt: "Photo 44",
  //     table_id: "n5emwq5c5dwepwam",
  //     table_name: "Three Card Poker",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Three Card Poker",
  //     gameTypeCode: "tcp",
  //   },
  //   {
  //     id: 45,
  //     src: "/images/photo45.png",
  //     alt: "Photo 45",
  //     table_id: "ndgvs3tqhfuaadyg",
  //     table_name: "Baccarat C DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Baccarat",
  //     gameTypeCode: "baccarat",
  //   },
  //   {
  //     id: 46,
  //     src: "/images/photo46.png",
  //     alt: "Photo 46",
  //     table_id: "nn2iutd5oerqayp5",
  //     table_name: "DHP DNT release QA",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "2 Hand Casino Hold'em",
  //     gameTypeCode: "dhp",
  //   },
  //   {
  //     id: 47,
  //     src: "/images/photo47.png",
  //     alt: "Photo 47",
  //     table_id: "NoCommBac0000001",
  //     table_name: "No Commission Baccarat DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Baccarat",
  //     gameTypeCode: "baccarat",
  //   },
  //   {
  //     id: 48,
  //     src: "/images/photo48.png",
  //     alt: "Photo 48",
  //     table_id: "nvonbym4lncqauzf",
  //     table_name: "PRQ 2HandPoker DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "2 Hand Casino Hold'em",
  //     gameTypeCode: "dhp",
  //   },
  //   {
  //     id: 49,
  //     src: "/images/photo49.png",
  //     alt: "Photo 49",
  //     table_id: "otctxzr5fjyggijz",
  //     table_name: "Hindi Roulette",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Roulette",
  //     gameTypeCode: "roulette",
  //   },
  //   {
  //     id: 50,
  //     src: "/images/photo50.png",
  //     alt: "Photo 50",
  //     table_id: "p33pav3difhqamv2",
  //     table_name: "AV money MOW",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Money Wheel",
  //     gameTypeCode: "moneywheel",
  //   },
  //   {
  //     id: 51,
  //     src: "/images/photo51.png",
  //     alt: "Photo 51",
  //     table_id: "p33rzklhc3xqawdr",
  //     table_name: "AV Monopoly",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Monopoly Live",
  //     gameTypeCode: "monopoly",
  //   },
  //   {
  //     id: 52,
  //     src: "/images/photo52.png",
  //     alt: "Photo 52",
  //     table_id: "peekbaccarat0001",
  //     table_name: "Peek Baccarat",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Baccarat",
  //     gameTypeCode: "baccarat",
  //   },
  //   {
  //     id: 53,
  //     src: "/images/photo53.png",
  //     alt: "Photo 53",
  //     table_id: "PTBaccarat000001",
  //     table_name: "Prosperity Tree Baccarat",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Baccarat",
  //     gameTypeCode: "baccarat",
  //   },
  //   {
  //     id: 54,
  //     src: "/images/photo54.png",
  //     alt: "Photo 54",
  //     table_id: "pwrxptpgeutaajyn",
  //     table_name: "Claudia_IBJ_DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Infinite Blackjack",
  //     gameTypeCode: "scalableblackjack",
  //   },
  //   {
  //     id: 55,
  //     src: "/images/photo55.png",
  //     alt: "Photo 55",
  //     table_id: "qp4zuimouyrqcava",
  //     table_name: "Football Studio Roulette",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Roulette",
  //     gameTypeCode: "roulette",
  //   },
  //   {
  //     id: 56,
  //     src: "/images/photo56.png",
  //     alt: "Photo 56",
  //     table_id: "qsc5mbqj7svaaeo4",
  //     table_name: "DT_PavTestLI DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Dragon Tiger",
  //     gameTypeCode: "dragontiger",
  //   },
  //   {
  //     id: 57,
  //     src: "/images/photo57.png",
  //     alt: "Photo 57",
  //     table_id: "RedDoorRoulette1",
  //     table_name: "Red Door Roulette",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Red Door Roulette",
  //     gameTypeCode: "reddoorroulette",
  //   },
  //   {
  //     id: 58,
  //     src: "/images/photo58.png",
  //     alt: "Photo 58",
  //     table_id: "rev2xgz6sjfqam4i",
  //     table_name: "Baccarat A DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Baccarat",
  //     gameTypeCode: "baccarat",
  //   },
  //   {
  //     id: 59,
  //     src: "/images/photo59.png",
  //     alt: "Photo 59",
  //     table_id: "rkfaxspyyoeqae3g",
  //     table_name: "BJ-11563 Test",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Blackjack",
  //     gameTypeCode: "blackjack",
  //   },
  //   {
  //     id: 60,
  //     src: "/images/photo60.png",
  //     alt: "Photo 60",
  //     table_id: "rng-bj-standard0",
  //     table_name: "First Person Blackjack DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "RNG Table Games",
  //     gameTypeName: "First Person Blackjack",
  //     gameTypeCode: "rng-blackjack",
  //   },
  //   {
  //     id: 61,
  //     src: "/images/photo61.png",
  //     alt: "Photo 61",
  //     table_id: "rng-dragontiger0",
  //     table_name: "First Person Dragon Tiger DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "RNG Table Games",
  //     gameTypeName: "First Person DragonTiger",
  //     gameTypeCode: "rng-dragontiger",
  //   },
  //   {
  //     id: 62,
  //     src: "/images/photo62.png",
  //     alt: "Photo 62",
  //     table_id: "rng-dreamcatcher",
  //     table_name: "First Person Dream Catcher",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "RNG Table Games",
  //     gameTypeName: "First Person Dream Catcher",
  //     gameTypeCode: "rng-moneywheel",
  //   },
  //   {
  //     id: 63,
  //     src: "/images/photo63.png",
  //     alt: "Photo 63",
  //     table_id: "rng-ptbaccarat01",
  //     table_name: "First Person Prosperity Tree Baccarat DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "RNG Table Games",
  //     gameTypeName: "First Person Baccarat",
  //     gameTypeCode: "rng-baccarat",
  //   },
  //   {
  //     id: 64,
  //     src: "/images/photo64.png",
  //     alt: "Photo 64",
  //     table_id: "rng-rt-european0",
  //     table_name: "First Person Roulette DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "RNG Table Games",
  //     gameTypeName: "First Person Roulette",
  //     gameTypeCode: "rng-roulette",
  //   },
  //   {
  //     id: 65,
  //     src: "/images/photo65.png",
  //     alt: "Photo 65",
  //     table_id: "rng-topcard00001",
  //     table_name: "First Person Top Card DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "RNG Table Games",
  //     gameTypeName: "First Person TopCard",
  //     gameTypeCode: "rng-topcard",
  //   },
  //   {
  //     id: 66,
  //     src: "/images/photo66.png",
  //     alt: "Photo 66",
  //     table_id: "rngbaccarat00000",
  //     table_name: "First Person Baccarat DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "RNG Table Games",
  //     gameTypeName: "First Person Baccarat",
  //     gameTypeCode: "rng-baccarat",
  //   },
  //   {
  //     id: 67,
  //     src: "/images/photo67.png",
  //     alt: "Photo 67",
  //     table_id: "RngCraps00000001",
  //     table_name: "First Person Craps DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "RNG Table Games",
  //     gameTypeName: "First Person Craps",
  //     gameTypeCode: "rng-craps",
  //   },
  //   {
  //     id: 68,
  //     src: "/images/photo68.png",
  //     alt: "Photo 68",
  //     table_id: "RngDealNoDeal001",
  //     table_name: "First Person Deal or No Deal DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "RNG Table Games",
  //     gameTypeName: "First Person Deal or No Deal",
  //     gameTypeCode: "rng-dealnodeal",
  //   },
  //   {
  //     id: 69,
  //     src: "/images/photo69.png",
  //     alt: "Photo 69",
  //     table_id: "rngLightning6001",
  //     table_name: "First Person Lightning Lotto DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "RNG Table Games",
  //     gameTypeName: "First Person Lightning Lotto",
  //     gameTypeCode: "rng-lightninglotto",
  //   },
  //   {
  //     id: 70,
  //     src: "/images/photo70.png",
  //     alt: "Photo 70",
  //     table_id: "RngMegaBall00001",
  //     table_name: "First Person Mega Ball DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "RNG Table Games",
  //     gameTypeName: "First Person Mega Ball",
  //     gameTypeCode: "rng-megaball",
  //   },
  //   {
  //     id: 71,
  //     src: "/images/photo71.png",
  //     alt: "Photo 71",
  //     table_id: "RngSicbo00000001",
  //     table_name: "First Person Super Sic Bo DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "RNG Table Games",
  //     gameTypeName: "First Person Super Sic Bo",
  //     gameTypeCode: "rng-sicbo",
  //   },
  //   {
  //     id: 72,
  //     src: "/images/photo72.png",
  //     alt: "Photo 72",
  //     table_id: "rtxhfhohzzbaehgd",
  //     table_name: "Mushegh BJ DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Blackjack",
  //     gameTypeCode: "blackjack",
  //   },
  //   {
  //     id: 73,
  //     src: "/images/photo73.png",
  //     alt: "Photo 73",
  //     table_id: "SBCTable00000001",
  //     table_name: "Side Bet City",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Side Bet City",
  //     gameTypeCode: "sidebetcity",
  //   },
  //   {
  //     id: 74,
  //     src: "/images/photo74.png",
  //     alt: "Photo 74",
  //     table_id: "SuperSicBo000001",
  //     table_name: "Super Sic Bo",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Super Sic Bo",
  //     gameTypeCode: "sicbo",
  //   },
  //   {
  //     id: 75,
  //     src: "/images/photo75.png",
  //     alt: "Photo 75",
  //     table_id: "teenpattitable01",
  //     table_name: "Teen Patti",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Teen Patti",
  //     gameTypeCode: "teenpatti",
  //   },
  //   {
  //     id: 76,
  //     src: "/images/photo76.png",
  //     alt: "Photo 76",
  //     table_id: "THBTable00000001",
  //     table_name: "Texas Hold'em Bonus Poker",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Texas Hold'em Bonus Poker",
  //     gameTypeCode: "thb",
  //   },
  //   {
  //     id: 77,
  //     src: "/images/photo77.png",
  //     alt: "Photo 77",
  //     table_id: "TopCard000000001",
  //     table_name: "Football studio",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Top Card",
  //     gameTypeCode: "topcard",
  //   },
  //   {
  //     id: 78,
  //     src: "/images/photo78.png",
  //     alt: "Photo 78",
  //     table_id: "TopDice000000001",
  //     table_name: "Football Studio Dice",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Top Dice",
  //     gameTypeCode: "topdice",
  //   },
  //   {
  //     id: 79,
  //     src: "/images/photo79.png",
  //     alt: "Photo 79",
  //     table_id: "TRPTable00000001",
  //     table_name: "Triple Card Poker",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Triple Card Poker",
  //     gameTypeCode: "trp",
  //   },
  //   {
  //     id: 80,
  //     src: "/images/photo80.png",
  //     alt: "Photo 80",
  //     table_id: "UTHTable00000001",
  //     table_name: "Ultimate Texas Hold'em",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Ultimate Texas Hold'em",
  //     gameTypeCode: "uth",
  //   },
  //   {
  //     id: 81,
  //     src: "/images/photo81.png",
  //     alt: "Photo 81",
  //     table_id: "uwd2bl2khwcikjlz",
  //     table_name: "Blackjack A DNT",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Blackjack",
  //     gameTypeCode: "blackjack",
  //   },
  //   {
  //     id: 82,
  //     src: "/images/photo82.png",
  //     alt: "Photo 82",
  //     table_id: "vctlz20yfnmp1ylr",
  //     table_name: "Roulette",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Roulette",
  //     gameTypeCode: "roulette",
  //   },
  //   {
  //     id: 83,
  //     src: "/images/photo83.png",
  //     alt: "Photo 83",
  //     table_id: "VPTable000000001",
  //     table_name: "Video Poker",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Video Poker",
  //     gameTypeCode: "videopoker",
  //   },
  //   {
  //     id: 84,
  //     src: "/images/photo84.png",
  //     alt: "Photo 84",
  //     table_id: "wzg6kdkad1oe7m5k",
  //     table_name: "VIP Roulette",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Roulette",
  //     gameTypeCode: "roulette",
  //   },
  //   {
  //     id: 85,
  //     src: "/images/photo85.png",
  //     alt: "Photo 85",
  //     table_id: "zixzea8nrf1675oh",
  //     table_name: "DNT Baccarat Squeeze (850)",
  //     gameProvider: "Evolution",
  //     subprovider: "",
  //     gameVertical: "Live",
  //     gameTypeName: "Baccarat",
  //     gameTypeCode: "baccarat",
  //   },
];

export default images;
